Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '/workspace/PredictIOR_Nextflow/R/getGeneAssociation.R': No such file or directory
Execution halted
